### ISSUE TITLE
Documentation - Add warning in "Create a Command" section to set environment [FEATURE]

### ISSUE THREAD

**Issue by jconabree** [absolunet/node-ioc#1]
Since the Installation documentation contains a lot of information only pertinent when installing on a server (pm2, HTTP proxy, etc), I missed the part where you have to setup the .env file. Because of this, there was only a very limited amount of commands available, so when reading sections like "Create a command" I was quite lost.

It would be nice to have the Environment section higher up on the page. Or in general, the installation page can be separated into sections that are **required** vs **optional**. Additionally it would be good to have a warning in the "Create a command" section mentioning that if the `make:command` isn't available, to visit a troubleshoot/install section.

Additionally, the Environment section can be separated into two paragraphs: Why we use the .env, and How to set it up. Right now it's easy to miss that you need to need to copy the .env.example to a .env.

**Comment by absolunet-admin** [comment]
The installation documentation was enhanced to provide clearer guidance over the environment file.
It would be nice of you to review it to make sure it is now more helpful for a quicker project initialization.

Thanks a lot for your input, much appreciated!
